/**
 * Bunny.net Storage Upload Utility
 * Uploads files from local disk to Bunny Storage after Payload saves them.
 * Uses Bunny Storage HTTP API (PUT).
 */

import fs from 'fs'
import path from 'path'

const BUNNY_STORAGE_ZONE = process.env.BUNNY_STORAGE_ZONE_NAME || ''
const BUNNY_STORAGE_PASSWORD = process.env.BUNNY_STORAGE_PASSWORD || ''
// Bunny Storage API endpoint (Frankfurt region by default; change if needed)
const BUNNY_STORAGE_HOST = 'https://storage.bunnycdn.com'

/**
 * Upload a single file to Bunny Storage.
 * @param localPath  Absolute path to the file on disk
 * @param remotePath Path within the storage zone (e.g. "/filename.webp")
 */
export async function uploadToBunny(localPath: string, remotePath: string): Promise<void> {
  if (!BUNNY_STORAGE_ZONE || !BUNNY_STORAGE_PASSWORD) {
    console.warn('[Bunny] BUNNY_STORAGE_ZONE_NAME or BUNNY_STORAGE_PASSWORD not set — skipping upload')
    return
  }

  if (!fs.existsSync(localPath)) {
    console.warn(`[Bunny] File not found on disk: ${localPath}`)
    return
  }

  const fileStream = fs.createReadStream(localPath)
  const fileSize = fs.statSync(localPath).size
  const url = `${BUNNY_STORAGE_HOST}/${BUNNY_STORAGE_ZONE}${remotePath}`

  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      AccessKey: BUNNY_STORAGE_PASSWORD,
      'Content-Type': 'application/octet-stream',
      'Content-Length': String(fileSize),
    },
    body: fileStream as any,
    // @ts-ignore — Node fetch supports ReadStream body
    duplex: 'half',
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    console.error(`[Bunny] Upload failed for ${remotePath}: ${response.status} ${response.statusText} — ${text}`)
  } else {
    console.log(`[Bunny] Uploaded: ${remotePath}`)
  }
}

/**
 * Given a Payload doc from the archivos collection, upload all image variants to Bunny.
 * Payload saves files in: <staticDir>/<filename>
 * The staticDir in Archivos.ts is: path.resolve(__dirname, '../../../media')  → /app/media (in production)
 */
export async function syncDocToBunny(doc: any): Promise<void> {
  if (!doc?.filename) return

  // Determine the media directory (same as staticDir in Archivos.ts)
  // In production the Dockerfile copies to /app, so media is at /app/media
  // We resolve relative to this file at runtime
  const mediaDir = path.resolve(process.cwd(), 'media')

  const filesToUpload: Array<{ local: string; remote: string }> = []

  // Main file
  filesToUpload.push({
    local: path.join(mediaDir, doc.filename),
    remote: `/${doc.filename}`,
  })

  // Image size variants generated by Payload
  if (doc.sizes) {
    for (const [, sizeData] of Object.entries(doc.sizes as Record<string, any>)) {
      if (sizeData?.filename) {
        filesToUpload.push({
          local: path.join(mediaDir, sizeData.filename),
          remote: `/${sizeData.filename}`,
        })
      }
    }
  }

  // Upload all variants in parallel
  await Promise.all(
    filesToUpload.map(({ local, remote }) => uploadToBunny(local, remote))
  )
}
