/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["es", "en", "fr", "de"]);
export const enum_usuarios_role = pgEnum("enum_usuarios_role", [
  "admin",
  "editor",
]);
export const enum_menus_dias_semana = pgEnum("enum_menus_dias_semana", [
  "lunes",
  "martes",
  "miercoles",
  "jueves",
  "viernes",
  "sabado",
  "domingo",
]);
export const enum_menus_horario = pgEnum("enum_menus_horario", [
  "comidas",
  "cenas",
  "ambos",
]);
export const enum_banners_posicion = pgEnum("enum_banners_posicion", [
  "home-top",
  "home-middle",
  "home-bottom",
  "carta-top",
  "menus-top",
  "global-top",
]);
export const enum_banners_tipo = pgEnum("enum_banners_tipo", [
  "info",
  "promo",
  "warning",
  "event",
]);
export const enum_configuracion_sitio_instagram_config_method = pgEnum(
  "enum_configuracion_sitio_instagram_config_method",
  ["api", "widget"],
);

export const usuarios_sessions = pgTable(
  "usuarios_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("usuarios_sessions_order_idx").on(columns._order),
    index("usuarios_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [usuarios.id],
      name: "usuarios_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const usuarios = pgTable(
  "usuarios",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    role: enum_usuarios_role("role").notNull().default("editor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("usuarios_updated_at_idx").on(columns.updatedAt),
    index("usuarios_created_at_idx").on(columns.createdAt),
    uniqueIndex("usuarios_email_idx").on(columns.email),
  ],
);

export const archivos = pgTable(
  "archivos",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("archivos_updated_at_idx").on(columns.updatedAt),
    index("archivos_created_at_idx").on(columns.createdAt),
    uniqueIndex("archivos_filename_idx").on(columns.filename),
    index("archivos_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("archivos_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("archivos_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const alergenos = pgTable(
  "alergenos",
  {
    id: serial("id").primaryKey(),
    codigo: varchar("codigo").notNull(),
    icono: varchar("icono"),
    imagen: integer("imagen_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    orden: numeric("orden", { mode: "number" }).notNull().default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("alergenos_imagen_idx").on(columns.imagen),
    index("alergenos_updated_at_idx").on(columns.updatedAt),
    index("alergenos_created_at_idx").on(columns.createdAt),
  ],
);

export const alergenos_locales = pgTable(
  "alergenos_locales",
  {
    nombre: varchar("nombre").notNull(),
    descripcion: varchar("descripcion"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("alergenos_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [alergenos.id],
      name: "alergenos_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const categorias = pgTable(
  "categorias",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    orden: numeric("orden", { mode: "number" }).notNull().default(1),
    activa: boolean("activa").default(true),
    imagen: integer("imagen_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categorias_slug_idx").on(columns.slug),
    index("categorias_imagen_idx").on(columns.imagen),
    index("categorias_updated_at_idx").on(columns.updatedAt),
    index("categorias_created_at_idx").on(columns.createdAt),
  ],
);

export const categorias_locales = pgTable(
  "categorias_locales",
  {
    nombre: varchar("nombre").notNull(),
    descripcion: varchar("descripcion"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("categorias_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [categorias.id],
      name: "categorias_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const platos_etiquetas = pgTable(
  "platos_etiquetas",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("platos_etiquetas_order_idx").on(columns._order),
    index("platos_etiquetas_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [platos.id],
      name: "platos_etiquetas_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const platos_etiquetas_locales = pgTable(
  "platos_etiquetas_locales",
  {
    etiqueta: varchar("etiqueta").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("platos_etiquetas_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [platos_etiquetas.id],
      name: "platos_etiquetas_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const platos = pgTable(
  "platos",
  {
    id: serial("id").primaryKey(),
    imagen: integer("imagen_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    categoria: integer("categoria_id")
      .notNull()
      .references(() => categorias.id, {
        onDelete: "set null",
      }),
    activo: boolean("activo").default(true),
    destacado: boolean("destacado").default(false),
    orden: numeric("orden", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("platos_imagen_idx").on(columns.imagen),
    index("platos_categoria_idx").on(columns.categoria),
    index("platos_updated_at_idx").on(columns.updatedAt),
    index("platos_created_at_idx").on(columns.createdAt),
  ],
);

export const platos_locales = pgTable(
  "platos_locales",
  {
    nombre: varchar("nombre").notNull(),
    descripcion: varchar("descripcion"),
    precio: varchar("precio").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("platos_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [platos.id],
      name: "platos_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const platos_rels = pgTable(
  "platos_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    alergenosID: integer("alergenos_id"),
  },
  (columns) => [
    index("platos_rels_order_idx").on(columns.order),
    index("platos_rels_parent_idx").on(columns.parent),
    index("platos_rels_path_idx").on(columns.path),
    index("platos_rels_alergenos_id_idx").on(columns.alergenosID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [platos.id],
      name: "platos_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["alergenosID"]],
      foreignColumns: [alergenos.id],
      name: "platos_rels_alergenos_fk",
    }).onDelete("cascade"),
  ],
);

export const menus_dias_semana = pgTable(
  "menus_dias_semana",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_menus_dias_semana("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("menus_dias_semana_order_idx").on(columns.order),
    index("menus_dias_semana_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [menus.id],
      name: "menus_dias_semana_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const menus = pgTable(
  "menus",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    imagen: integer("imagen_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    precio: numeric("precio", { mode: "number" }).notNull(),
    fechaInicio: timestamp("fecha_inicio", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    fechaFin: timestamp("fecha_fin", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    pdf: integer("pdf_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    activo: boolean("activo").default(true),
    destacado: boolean("destacado").default(false),
    orden: numeric("orden", { mode: "number" }).default(0),
    horario: enum_menus_horario("horario"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("menus_slug_idx").on(columns.slug),
    index("menus_imagen_idx").on(columns.imagen),
    index("menus_pdf_idx").on(columns.pdf),
    index("menus_updated_at_idx").on(columns.updatedAt),
    index("menus_created_at_idx").on(columns.createdAt),
  ],
);

export const menus_locales = pgTable(
  "menus_locales",
  {
    nombre: varchar("nombre").notNull(),
    etiqueta: varchar("etiqueta"),
    descripcion_menu: varchar("descripcion_menu"),
    fechasDias: varchar("fechas_dias"),
    descripcion: jsonb("descripcion"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("menus_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menus.id],
      name: "menus_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const espacios_galeria = pgTable(
  "espacios_galeria",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    imagen: integer("imagen_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("espacios_galeria_order_idx").on(columns._order),
    index("espacios_galeria_parent_id_idx").on(columns._parentID),
    index("espacios_galeria_imagen_idx").on(columns.imagen),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [espacios.id],
      name: "espacios_galeria_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const espacios_caracteristicas = pgTable(
  "espacios_caracteristicas",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("espacios_caracteristicas_order_idx").on(columns._order),
    index("espacios_caracteristicas_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [espacios.id],
      name: "espacios_caracteristicas_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const espacios_caracteristicas_locales = pgTable(
  "espacios_caracteristicas_locales",
  {
    caracteristica: varchar("caracteristica").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("espacios_caracteristicas_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [espacios_caracteristicas.id],
      name: "espacios_caracteristicas_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const espacios = pgTable(
  "espacios",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    capacidad: numeric("capacidad", { mode: "number" }),
    orden: numeric("orden", { mode: "number" }).notNull().default(0),
    activo: boolean("activo").default(true),
    disponibleEventos: boolean("disponible_eventos").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("espacios_slug_idx").on(columns.slug),
    index("espacios_updated_at_idx").on(columns.updatedAt),
    index("espacios_created_at_idx").on(columns.createdAt),
  ],
);

export const espacios_locales = pgTable(
  "espacios_locales",
  {
    nombre: varchar("nombre").notNull(),
    descripcion: jsonb("descripcion"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("espacios_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [espacios.id],
      name: "espacios_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const banners = pgTable(
  "banners",
  {
    id: serial("id").primaryKey(),
    imagen: integer("imagen_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    link_url: varchar("link_url"),
    link_externo: boolean("link_externo").default(false),
    fechaInicio: timestamp("fecha_inicio", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    fechaFin: timestamp("fecha_fin", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    posicion: enum_banners_posicion("posicion").notNull(),
    tipo: enum_banners_tipo("tipo"),
    activo: boolean("activo").default(true),
    prioridad: numeric("prioridad", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("banners_imagen_idx").on(columns.imagen),
    index("banners_updated_at_idx").on(columns.updatedAt),
    index("banners_created_at_idx").on(columns.createdAt),
  ],
);

export const banners_locales = pgTable(
  "banners_locales",
  {
    titulo: varchar("titulo").notNull(),
    texto: varchar("texto"),
    link_texto: varchar("link_texto"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("banners_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [banners.id],
      name: "banners_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const paginas = pgTable(
  "paginas",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    heroImage: integer("hero_image_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
    imagenEspacio1: integer("imagen_espacio1_id").references(
      () => archivos.id,
      {
        onDelete: "set null",
      },
    ),
    imagenEspacio2: integer("imagen_espacio2_id").references(
      () => archivos.id,
      {
        onDelete: "set null",
      },
    ),
    imagenEspacio3: integer("imagen_espacio3_id").references(
      () => archivos.id,
      {
        onDelete: "set null",
      },
    ),
    imagenEspacio4: integer("imagen_espacio4_id").references(
      () => archivos.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("paginas_slug_idx").on(columns.slug),
    index("paginas_hero_image_idx").on(columns.heroImage),
    index("paginas_imagen_espacio1_idx").on(columns.imagenEspacio1),
    index("paginas_imagen_espacio2_idx").on(columns.imagenEspacio2),
    index("paginas_imagen_espacio3_idx").on(columns.imagenEspacio3),
    index("paginas_imagen_espacio4_idx").on(columns.imagenEspacio4),
    index("paginas_updated_at_idx").on(columns.updatedAt),
    index("paginas_created_at_idx").on(columns.createdAt),
  ],
);

export const paginas_locales = pgTable(
  "paginas_locales",
  {
    tituloInterno: varchar("titulo_interno").notNull(),
    heroTitle: varchar("hero_title"),
    heroSubtitle: varchar("hero_subtitle"),
    metaTitle: varchar("meta_title"),
    metaDescription: varchar("meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("paginas_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [paginas.id],
      name: "paginas_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const experiencias_incluye = pgTable(
  "experiencias_incluye",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("experiencias_incluye_order_idx").on(columns._order),
    index("experiencias_incluye_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [experiencias.id],
      name: "experiencias_incluye_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const experiencias_incluye_locales = pgTable(
  "experiencias_incluye_locales",
  {
    item: varchar("item").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("experiencias_incluye_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [experiencias_incluye.id],
      name: "experiencias_incluye_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const experiencias = pgTable(
  "experiencias",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    precio: numeric("precio", { mode: "number" }).notNull(),
    imagen: integer("imagen_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
    linkCompra: varchar("link_compra"),
    colorFondo: varchar("color_fondo"),
    activo: boolean("activo").default(true),
    destacado: boolean("destacado").default(false),
    orden: numeric("orden", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("experiencias_slug_idx").on(columns.slug),
    index("experiencias_imagen_idx").on(columns.imagen),
    index("experiencias_updated_at_idx").on(columns.updatedAt),
    index("experiencias_created_at_idx").on(columns.createdAt),
  ],
);

export const experiencias_locales = pgTable(
  "experiencias_locales",
  {
    titulo: varchar("titulo").notNull(),
    descripcion: jsonb("descripcion"),
    resumen: varchar("resumen"),
    validez: varchar("validez"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("experiencias_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [experiencias.id],
      name: "experiencias_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const menus_grupo = pgTable(
  "menus_grupo",
  {
    id: serial("id").primaryKey(),
    imagenPortada: integer("imagen_portada_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    orden: numeric("orden", { mode: "number" }).default(0),
    activo: boolean("activo").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("menus_grupo_imagen_portada_idx").on(columns.imagenPortada),
    index("menus_grupo_updated_at_idx").on(columns.updatedAt),
    index("menus_grupo_created_at_idx").on(columns.createdAt),
  ],
);

export const menus_grupo_locales = pgTable(
  "menus_grupo_locales",
  {
    nombre: varchar("nombre").notNull(),
    descripcion: varchar("descripcion"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("menus_grupo_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [menus_grupo.id],
      name: "menus_grupo_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const menus_grupo_rels = pgTable(
  "menus_grupo_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    menusID: integer("menus_id"),
  },
  (columns) => [
    index("menus_grupo_rels_order_idx").on(columns.order),
    index("menus_grupo_rels_parent_idx").on(columns.parent),
    index("menus_grupo_rels_path_idx").on(columns.path),
    index("menus_grupo_rels_menus_id_idx").on(columns.menusID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [menus_grupo.id],
      name: "menus_grupo_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["menusID"]],
      foreignColumns: [menus.id],
      name: "menus_grupo_rels_menus_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usuariosID: integer("usuarios_id"),
    archivosID: integer("archivos_id"),
    alergenosID: integer("alergenos_id"),
    categoriasID: integer("categorias_id"),
    platosID: integer("platos_id"),
    menusID: integer("menus_id"),
    espaciosID: integer("espacios_id"),
    bannersID: integer("banners_id"),
    paginasID: integer("paginas_id"),
    experienciasID: integer("experiencias_id"),
    "menus-grupoID": integer("menus_grupo_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_usuarios_id_idx").on(
      columns.usuariosID,
    ),
    index("payload_locked_documents_rels_archivos_id_idx").on(
      columns.archivosID,
    ),
    index("payload_locked_documents_rels_alergenos_id_idx").on(
      columns.alergenosID,
    ),
    index("payload_locked_documents_rels_categorias_id_idx").on(
      columns.categoriasID,
    ),
    index("payload_locked_documents_rels_platos_id_idx").on(columns.platosID),
    index("payload_locked_documents_rels_menus_id_idx").on(columns.menusID),
    index("payload_locked_documents_rels_espacios_id_idx").on(
      columns.espaciosID,
    ),
    index("payload_locked_documents_rels_banners_id_idx").on(columns.bannersID),
    index("payload_locked_documents_rels_paginas_id_idx").on(columns.paginasID),
    index("payload_locked_documents_rels_experiencias_id_idx").on(
      columns.experienciasID,
    ),
    index("payload_locked_documents_rels_menus_grupo_id_idx").on(
      columns["menus-grupoID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usuariosID"]],
      foreignColumns: [usuarios.id],
      name: "payload_locked_documents_rels_usuarios_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["archivosID"]],
      foreignColumns: [archivos.id],
      name: "payload_locked_documents_rels_archivos_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["alergenosID"]],
      foreignColumns: [alergenos.id],
      name: "payload_locked_documents_rels_alergenos_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriasID"]],
      foreignColumns: [categorias.id],
      name: "payload_locked_documents_rels_categorias_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["platosID"]],
      foreignColumns: [platos.id],
      name: "payload_locked_documents_rels_platos_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["menusID"]],
      foreignColumns: [menus.id],
      name: "payload_locked_documents_rels_menus_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["espaciosID"]],
      foreignColumns: [espacios.id],
      name: "payload_locked_documents_rels_espacios_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["bannersID"]],
      foreignColumns: [banners.id],
      name: "payload_locked_documents_rels_banners_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["paginasID"]],
      foreignColumns: [paginas.id],
      name: "payload_locked_documents_rels_paginas_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["experienciasID"]],
      foreignColumns: [experiencias.id],
      name: "payload_locked_documents_rels_experiencias_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["menus-grupoID"]],
      foreignColumns: [menus_grupo.id],
      name: "payload_locked_documents_rels_menus_grupo_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usuariosID: integer("usuarios_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_usuarios_id_idx").on(columns.usuariosID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usuariosID"]],
      foreignColumns: [usuarios.id],
      name: "payload_preferences_rels_usuarios_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const pagina_inicio_galeria_inicio = pgTable(
  "pagina_inicio_galeria_inicio",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    imagen: integer("imagen_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("pagina_inicio_galeria_inicio_order_idx").on(columns._order),
    index("pagina_inicio_galeria_inicio_parent_id_idx").on(columns._parentID),
    index("pagina_inicio_galeria_inicio_imagen_idx").on(columns.imagen),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pagina_inicio.id],
      name: "pagina_inicio_galeria_inicio_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pagina_inicio_galeria_regalo = pgTable(
  "pagina_inicio_galeria_regalo",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    imagen: integer("imagen_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("pagina_inicio_galeria_regalo_order_idx").on(columns._order),
    index("pagina_inicio_galeria_regalo_parent_id_idx").on(columns._parentID),
    index("pagina_inicio_galeria_regalo_imagen_idx").on(columns.imagen),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pagina_inicio.id],
      name: "pagina_inicio_galeria_regalo_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pagina_inicio = pgTable(
  "pagina_inicio",
  {
    id: serial("id").primaryKey(),
    heroImage: integer("hero_image_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("pagina_inicio_hero_image_idx").on(columns.heroImage)],
);

export const pagina_inicio_locales = pgTable(
  "pagina_inicio_locales",
  {
    heroTitle: varchar("hero_title").notNull(),
    heroSubtitle: varchar("hero_subtitle"),
    welcomeTitle: varchar("welcome_title"),
    welcomeText: jsonb("welcome_text"),
    ctaTitle: varchar("cta_title"),
    ctaText: varchar("cta_text"),
    ctaButtonText: varchar("cta_button_text").default("Reservar ahora"),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pagina_inicio_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pagina_inicio.id],
      name: "pagina_inicio_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pagina_inicio_rels = pgTable(
  "pagina_inicio_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    espaciosID: integer("espacios_id"),
    experienciasID: integer("experiencias_id"),
  },
  (columns) => [
    index("pagina_inicio_rels_order_idx").on(columns.order),
    index("pagina_inicio_rels_parent_idx").on(columns.parent),
    index("pagina_inicio_rels_path_idx").on(columns.path),
    index("pagina_inicio_rels_espacios_id_idx").on(columns.espaciosID),
    index("pagina_inicio_rels_experiencias_id_idx").on(columns.experienciasID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [pagina_inicio.id],
      name: "pagina_inicio_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["espaciosID"]],
      foreignColumns: [espacios.id],
      name: "pagina_inicio_rels_espacios_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["experienciasID"]],
      foreignColumns: [experiencias.id],
      name: "pagina_inicio_rels_experiencias_fk",
    }).onDelete("cascade"),
  ],
);

export const configuracion_sitio_opening_hours = pgTable(
  "configuracion_sitio_opening_hours",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    closed: boolean("closed").default(false),
  },
  (columns) => [
    index("configuracion_sitio_opening_hours_order_idx").on(columns._order),
    index("configuracion_sitio_opening_hours_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [configuracion_sitio.id],
      name: "configuracion_sitio_opening_hours_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const configuracion_sitio_opening_hours_locales = pgTable(
  "configuracion_sitio_opening_hours_locales",
  {
    days: varchar("days"),
    hours: varchar("hours"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "configuracion_sitio_opening_hours_locales_locale_parent_id_u",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [configuracion_sitio_opening_hours.id],
      name: "configuracion_sitio_opening_hours_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const configuracion_sitio_footer_logos = pgTable(
  "configuracion_sitio_footer_logos",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    logo: integer("logo_id")
      .notNull()
      .references(() => archivos.id, {
        onDelete: "set null",
      }),
    link: varchar("link"),
  },
  (columns) => [
    index("configuracion_sitio_footer_logos_order_idx").on(columns._order),
    index("configuracion_sitio_footer_logos_parent_id_idx").on(
      columns._parentID,
    ),
    index("configuracion_sitio_footer_logos_logo_idx").on(columns.logo),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [configuracion_sitio.id],
      name: "configuracion_sitio_footer_logos_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const configuracion_sitio_footer_logos_locales = pgTable(
  "configuracion_sitio_footer_logos_locales",
  {
    alt: varchar("alt").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "configuracion_sitio_footer_logos_locales_locale_parent_id_un",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [configuracion_sitio_footer_logos.id],
      name: "configuracion_sitio_footer_logos_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const configuracion_sitio = pgTable(
  "configuracion_sitio",
  {
    id: serial("id").primaryKey(),
    logo: integer("logo_id").references(() => archivos.id, {
      onDelete: "set null",
    }),
    contact_phone: varchar("contact_phone"),
    contact_whatsapp: varchar("contact_whatsapp"),
    contact_email: varchar("contact_email"),
    contact_postalCode: varchar("contact_postal_code"),
    contact_city: varchar("contact_city"),
    contact_province: varchar("contact_province"),
    contact_country: varchar("contact_country"),
    contact_googleMapsUrl: varchar("contact_google_maps_url"),
    contact_coordinates_lat: numeric("contact_coordinates_lat", {
      mode: "number",
    }),
    contact_coordinates_lng: numeric("contact_coordinates_lng", {
      mode: "number",
    }),
    socialMedia_facebook: varchar("social_media_facebook"),
    socialMedia_instagram: varchar("social_media_instagram"),
    socialMedia_twitter: varchar("social_media_twitter"),
    socialMedia_tiktok: varchar("social_media_tiktok"),
    socialMedia_youtube: varchar("social_media_youtube"),
    socialMedia_tripadvisor: varchar("social_media_tripadvisor"),
    coverManagerId: varchar("cover_manager_id"),
    instagramConfig_method: enum_configuracion_sitio_instagram_config_method(
      "instagram_config_method",
    ).default("api"),
    instagramConfig_apiToken: varchar("instagram_config_api_token"),
    instagramConfig_apiUserId: varchar("instagram_config_api_user_id"),
    instagramConfig_embedCode: varchar("instagram_config_embed_code"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("configuracion_sitio_logo_idx").on(columns.logo)],
);

export const configuracion_sitio_locales = pgTable(
  "configuracion_sitio_locales",
  {
    title: varchar("title").notNull(),
    description: varchar("description"),
    contact_whatsappMessage: varchar("contact_whatsapp_message"),
    contact_address: varchar("contact_address"),
    copyright: varchar("copyright"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("configuracion_sitio_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [configuracion_sitio.id],
      name: "configuracion_sitio_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_usuarios_sessions = relations(
  usuarios_sessions,
  ({ one }) => ({
    _parentID: one(usuarios, {
      fields: [usuarios_sessions._parentID],
      references: [usuarios.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_usuarios = relations(usuarios, ({ many }) => ({
  sessions: many(usuarios_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_archivos = relations(archivos, () => ({}));
export const relations_alergenos_locales = relations(
  alergenos_locales,
  ({ one }) => ({
    _parentID: one(alergenos, {
      fields: [alergenos_locales._parentID],
      references: [alergenos.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_alergenos = relations(alergenos, ({ one, many }) => ({
  imagen: one(archivos, {
    fields: [alergenos.imagen],
    references: [archivos.id],
    relationName: "imagen",
  }),
  _locales: many(alergenos_locales, {
    relationName: "_locales",
  }),
}));
export const relations_categorias_locales = relations(
  categorias_locales,
  ({ one }) => ({
    _parentID: one(categorias, {
      fields: [categorias_locales._parentID],
      references: [categorias.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_categorias = relations(categorias, ({ one, many }) => ({
  imagen: one(archivos, {
    fields: [categorias.imagen],
    references: [archivos.id],
    relationName: "imagen",
  }),
  _locales: many(categorias_locales, {
    relationName: "_locales",
  }),
}));
export const relations_platos_etiquetas_locales = relations(
  platos_etiquetas_locales,
  ({ one }) => ({
    _parentID: one(platos_etiquetas, {
      fields: [platos_etiquetas_locales._parentID],
      references: [platos_etiquetas.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_platos_etiquetas = relations(
  platos_etiquetas,
  ({ one, many }) => ({
    _parentID: one(platos, {
      fields: [platos_etiquetas._parentID],
      references: [platos.id],
      relationName: "etiquetas",
    }),
    _locales: many(platos_etiquetas_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_platos_locales = relations(
  platos_locales,
  ({ one }) => ({
    _parentID: one(platos, {
      fields: [platos_locales._parentID],
      references: [platos.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_platos_rels = relations(platos_rels, ({ one }) => ({
  parent: one(platos, {
    fields: [platos_rels.parent],
    references: [platos.id],
    relationName: "_rels",
  }),
  alergenosID: one(alergenos, {
    fields: [platos_rels.alergenosID],
    references: [alergenos.id],
    relationName: "alergenos",
  }),
}));
export const relations_platos = relations(platos, ({ one, many }) => ({
  imagen: one(archivos, {
    fields: [platos.imagen],
    references: [archivos.id],
    relationName: "imagen",
  }),
  categoria: one(categorias, {
    fields: [platos.categoria],
    references: [categorias.id],
    relationName: "categoria",
  }),
  etiquetas: many(platos_etiquetas, {
    relationName: "etiquetas",
  }),
  _locales: many(platos_locales, {
    relationName: "_locales",
  }),
  _rels: many(platos_rels, {
    relationName: "_rels",
  }),
}));
export const relations_menus_dias_semana = relations(
  menus_dias_semana,
  ({ one }) => ({
    parent: one(menus, {
      fields: [menus_dias_semana.parent],
      references: [menus.id],
      relationName: "diasSemana",
    }),
  }),
);
export const relations_menus_locales = relations(menus_locales, ({ one }) => ({
  _parentID: one(menus, {
    fields: [menus_locales._parentID],
    references: [menus.id],
    relationName: "_locales",
  }),
}));
export const relations_menus = relations(menus, ({ one, many }) => ({
  imagen: one(archivos, {
    fields: [menus.imagen],
    references: [archivos.id],
    relationName: "imagen",
  }),
  pdf: one(archivos, {
    fields: [menus.pdf],
    references: [archivos.id],
    relationName: "pdf",
  }),
  diasSemana: many(menus_dias_semana, {
    relationName: "diasSemana",
  }),
  _locales: many(menus_locales, {
    relationName: "_locales",
  }),
}));
export const relations_espacios_galeria = relations(
  espacios_galeria,
  ({ one }) => ({
    _parentID: one(espacios, {
      fields: [espacios_galeria._parentID],
      references: [espacios.id],
      relationName: "galeria",
    }),
    imagen: one(archivos, {
      fields: [espacios_galeria.imagen],
      references: [archivos.id],
      relationName: "imagen",
    }),
  }),
);
export const relations_espacios_caracteristicas_locales = relations(
  espacios_caracteristicas_locales,
  ({ one }) => ({
    _parentID: one(espacios_caracteristicas, {
      fields: [espacios_caracteristicas_locales._parentID],
      references: [espacios_caracteristicas.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_espacios_caracteristicas = relations(
  espacios_caracteristicas,
  ({ one, many }) => ({
    _parentID: one(espacios, {
      fields: [espacios_caracteristicas._parentID],
      references: [espacios.id],
      relationName: "caracteristicas",
    }),
    _locales: many(espacios_caracteristicas_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_espacios_locales = relations(
  espacios_locales,
  ({ one }) => ({
    _parentID: one(espacios, {
      fields: [espacios_locales._parentID],
      references: [espacios.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_espacios = relations(espacios, ({ many }) => ({
  galeria: many(espacios_galeria, {
    relationName: "galeria",
  }),
  caracteristicas: many(espacios_caracteristicas, {
    relationName: "caracteristicas",
  }),
  _locales: many(espacios_locales, {
    relationName: "_locales",
  }),
}));
export const relations_banners_locales = relations(
  banners_locales,
  ({ one }) => ({
    _parentID: one(banners, {
      fields: [banners_locales._parentID],
      references: [banners.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_banners = relations(banners, ({ one, many }) => ({
  imagen: one(archivos, {
    fields: [banners.imagen],
    references: [archivos.id],
    relationName: "imagen",
  }),
  _locales: many(banners_locales, {
    relationName: "_locales",
  }),
}));
export const relations_paginas_locales = relations(
  paginas_locales,
  ({ one }) => ({
    _parentID: one(paginas, {
      fields: [paginas_locales._parentID],
      references: [paginas.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_paginas = relations(paginas, ({ one, many }) => ({
  heroImage: one(archivos, {
    fields: [paginas.heroImage],
    references: [archivos.id],
    relationName: "heroImage",
  }),
  imagenEspacio1: one(archivos, {
    fields: [paginas.imagenEspacio1],
    references: [archivos.id],
    relationName: "imagenEspacio1",
  }),
  imagenEspacio2: one(archivos, {
    fields: [paginas.imagenEspacio2],
    references: [archivos.id],
    relationName: "imagenEspacio2",
  }),
  imagenEspacio3: one(archivos, {
    fields: [paginas.imagenEspacio3],
    references: [archivos.id],
    relationName: "imagenEspacio3",
  }),
  imagenEspacio4: one(archivos, {
    fields: [paginas.imagenEspacio4],
    references: [archivos.id],
    relationName: "imagenEspacio4",
  }),
  _locales: many(paginas_locales, {
    relationName: "_locales",
  }),
}));
export const relations_experiencias_incluye_locales = relations(
  experiencias_incluye_locales,
  ({ one }) => ({
    _parentID: one(experiencias_incluye, {
      fields: [experiencias_incluye_locales._parentID],
      references: [experiencias_incluye.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_experiencias_incluye = relations(
  experiencias_incluye,
  ({ one, many }) => ({
    _parentID: one(experiencias, {
      fields: [experiencias_incluye._parentID],
      references: [experiencias.id],
      relationName: "incluye",
    }),
    _locales: many(experiencias_incluye_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_experiencias_locales = relations(
  experiencias_locales,
  ({ one }) => ({
    _parentID: one(experiencias, {
      fields: [experiencias_locales._parentID],
      references: [experiencias.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_experiencias = relations(
  experiencias,
  ({ one, many }) => ({
    imagen: one(archivos, {
      fields: [experiencias.imagen],
      references: [archivos.id],
      relationName: "imagen",
    }),
    incluye: many(experiencias_incluye, {
      relationName: "incluye",
    }),
    _locales: many(experiencias_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_menus_grupo_locales = relations(
  menus_grupo_locales,
  ({ one }) => ({
    _parentID: one(menus_grupo, {
      fields: [menus_grupo_locales._parentID],
      references: [menus_grupo.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_menus_grupo_rels = relations(
  menus_grupo_rels,
  ({ one }) => ({
    parent: one(menus_grupo, {
      fields: [menus_grupo_rels.parent],
      references: [menus_grupo.id],
      relationName: "_rels",
    }),
    menusID: one(menus, {
      fields: [menus_grupo_rels.menusID],
      references: [menus.id],
      relationName: "menus",
    }),
  }),
);
export const relations_menus_grupo = relations(
  menus_grupo,
  ({ one, many }) => ({
    imagenPortada: one(archivos, {
      fields: [menus_grupo.imagenPortada],
      references: [archivos.id],
      relationName: "imagenPortada",
    }),
    _locales: many(menus_grupo_locales, {
      relationName: "_locales",
    }),
    _rels: many(menus_grupo_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usuariosID: one(usuarios, {
      fields: [payload_locked_documents_rels.usuariosID],
      references: [usuarios.id],
      relationName: "usuarios",
    }),
    archivosID: one(archivos, {
      fields: [payload_locked_documents_rels.archivosID],
      references: [archivos.id],
      relationName: "archivos",
    }),
    alergenosID: one(alergenos, {
      fields: [payload_locked_documents_rels.alergenosID],
      references: [alergenos.id],
      relationName: "alergenos",
    }),
    categoriasID: one(categorias, {
      fields: [payload_locked_documents_rels.categoriasID],
      references: [categorias.id],
      relationName: "categorias",
    }),
    platosID: one(platos, {
      fields: [payload_locked_documents_rels.platosID],
      references: [platos.id],
      relationName: "platos",
    }),
    menusID: one(menus, {
      fields: [payload_locked_documents_rels.menusID],
      references: [menus.id],
      relationName: "menus",
    }),
    espaciosID: one(espacios, {
      fields: [payload_locked_documents_rels.espaciosID],
      references: [espacios.id],
      relationName: "espacios",
    }),
    bannersID: one(banners, {
      fields: [payload_locked_documents_rels.bannersID],
      references: [banners.id],
      relationName: "banners",
    }),
    paginasID: one(paginas, {
      fields: [payload_locked_documents_rels.paginasID],
      references: [paginas.id],
      relationName: "paginas",
    }),
    experienciasID: one(experiencias, {
      fields: [payload_locked_documents_rels.experienciasID],
      references: [experiencias.id],
      relationName: "experiencias",
    }),
    "menus-grupoID": one(menus_grupo, {
      fields: [payload_locked_documents_rels["menus-grupoID"]],
      references: [menus_grupo.id],
      relationName: "menus-grupo",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usuariosID: one(usuarios, {
      fields: [payload_preferences_rels.usuariosID],
      references: [usuarios.id],
      relationName: "usuarios",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_pagina_inicio_galeria_inicio = relations(
  pagina_inicio_galeria_inicio,
  ({ one }) => ({
    _parentID: one(pagina_inicio, {
      fields: [pagina_inicio_galeria_inicio._parentID],
      references: [pagina_inicio.id],
      relationName: "galeriaInicio",
    }),
    imagen: one(archivos, {
      fields: [pagina_inicio_galeria_inicio.imagen],
      references: [archivos.id],
      relationName: "imagen",
    }),
  }),
);
export const relations_pagina_inicio_galeria_regalo = relations(
  pagina_inicio_galeria_regalo,
  ({ one }) => ({
    _parentID: one(pagina_inicio, {
      fields: [pagina_inicio_galeria_regalo._parentID],
      references: [pagina_inicio.id],
      relationName: "galeriaRegalo",
    }),
    imagen: one(archivos, {
      fields: [pagina_inicio_galeria_regalo.imagen],
      references: [archivos.id],
      relationName: "imagen",
    }),
  }),
);
export const relations_pagina_inicio_locales = relations(
  pagina_inicio_locales,
  ({ one }) => ({
    _parentID: one(pagina_inicio, {
      fields: [pagina_inicio_locales._parentID],
      references: [pagina_inicio.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pagina_inicio_rels = relations(
  pagina_inicio_rels,
  ({ one }) => ({
    parent: one(pagina_inicio, {
      fields: [pagina_inicio_rels.parent],
      references: [pagina_inicio.id],
      relationName: "_rels",
    }),
    espaciosID: one(espacios, {
      fields: [pagina_inicio_rels.espaciosID],
      references: [espacios.id],
      relationName: "espacios",
    }),
    experienciasID: one(experiencias, {
      fields: [pagina_inicio_rels.experienciasID],
      references: [experiencias.id],
      relationName: "experiencias",
    }),
  }),
);
export const relations_pagina_inicio = relations(
  pagina_inicio,
  ({ one, many }) => ({
    heroImage: one(archivos, {
      fields: [pagina_inicio.heroImage],
      references: [archivos.id],
      relationName: "heroImage",
    }),
    galeriaInicio: many(pagina_inicio_galeria_inicio, {
      relationName: "galeriaInicio",
    }),
    galeriaRegalo: many(pagina_inicio_galeria_regalo, {
      relationName: "galeriaRegalo",
    }),
    _locales: many(pagina_inicio_locales, {
      relationName: "_locales",
    }),
    _rels: many(pagina_inicio_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_configuracion_sitio_opening_hours_locales = relations(
  configuracion_sitio_opening_hours_locales,
  ({ one }) => ({
    _parentID: one(configuracion_sitio_opening_hours, {
      fields: [configuracion_sitio_opening_hours_locales._parentID],
      references: [configuracion_sitio_opening_hours.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_configuracion_sitio_opening_hours = relations(
  configuracion_sitio_opening_hours,
  ({ one, many }) => ({
    _parentID: one(configuracion_sitio, {
      fields: [configuracion_sitio_opening_hours._parentID],
      references: [configuracion_sitio.id],
      relationName: "openingHours",
    }),
    _locales: many(configuracion_sitio_opening_hours_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_configuracion_sitio_footer_logos_locales = relations(
  configuracion_sitio_footer_logos_locales,
  ({ one }) => ({
    _parentID: one(configuracion_sitio_footer_logos, {
      fields: [configuracion_sitio_footer_logos_locales._parentID],
      references: [configuracion_sitio_footer_logos.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_configuracion_sitio_footer_logos = relations(
  configuracion_sitio_footer_logos,
  ({ one, many }) => ({
    _parentID: one(configuracion_sitio, {
      fields: [configuracion_sitio_footer_logos._parentID],
      references: [configuracion_sitio.id],
      relationName: "footerLogos",
    }),
    _locales: many(configuracion_sitio_footer_logos_locales, {
      relationName: "_locales",
    }),
    logo: one(archivos, {
      fields: [configuracion_sitio_footer_logos.logo],
      references: [archivos.id],
      relationName: "logo",
    }),
  }),
);
export const relations_configuracion_sitio_locales = relations(
  configuracion_sitio_locales,
  ({ one }) => ({
    _parentID: one(configuracion_sitio, {
      fields: [configuracion_sitio_locales._parentID],
      references: [configuracion_sitio.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_configuracion_sitio = relations(
  configuracion_sitio,
  ({ one, many }) => ({
    logo: one(archivos, {
      fields: [configuracion_sitio.logo],
      references: [archivos.id],
      relationName: "logo",
    }),
    openingHours: many(configuracion_sitio_opening_hours, {
      relationName: "openingHours",
    }),
    footerLogos: many(configuracion_sitio_footer_logos, {
      relationName: "footerLogos",
    }),
    _locales: many(configuracion_sitio_locales, {
      relationName: "_locales",
    }),
  }),
);

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_usuarios_role: typeof enum_usuarios_role;
  enum_menus_dias_semana: typeof enum_menus_dias_semana;
  enum_menus_horario: typeof enum_menus_horario;
  enum_banners_posicion: typeof enum_banners_posicion;
  enum_banners_tipo: typeof enum_banners_tipo;
  enum_configuracion_sitio_instagram_config_method: typeof enum_configuracion_sitio_instagram_config_method;
  usuarios_sessions: typeof usuarios_sessions;
  usuarios: typeof usuarios;
  archivos: typeof archivos;
  alergenos: typeof alergenos;
  alergenos_locales: typeof alergenos_locales;
  categorias: typeof categorias;
  categorias_locales: typeof categorias_locales;
  platos_etiquetas: typeof platos_etiquetas;
  platos_etiquetas_locales: typeof platos_etiquetas_locales;
  platos: typeof platos;
  platos_locales: typeof platos_locales;
  platos_rels: typeof platos_rels;
  menus_dias_semana: typeof menus_dias_semana;
  menus: typeof menus;
  menus_locales: typeof menus_locales;
  espacios_galeria: typeof espacios_galeria;
  espacios_caracteristicas: typeof espacios_caracteristicas;
  espacios_caracteristicas_locales: typeof espacios_caracteristicas_locales;
  espacios: typeof espacios;
  espacios_locales: typeof espacios_locales;
  banners: typeof banners;
  banners_locales: typeof banners_locales;
  paginas: typeof paginas;
  paginas_locales: typeof paginas_locales;
  experiencias_incluye: typeof experiencias_incluye;
  experiencias_incluye_locales: typeof experiencias_incluye_locales;
  experiencias: typeof experiencias;
  experiencias_locales: typeof experiencias_locales;
  menus_grupo: typeof menus_grupo;
  menus_grupo_locales: typeof menus_grupo_locales;
  menus_grupo_rels: typeof menus_grupo_rels;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  pagina_inicio_galeria_inicio: typeof pagina_inicio_galeria_inicio;
  pagina_inicio_galeria_regalo: typeof pagina_inicio_galeria_regalo;
  pagina_inicio: typeof pagina_inicio;
  pagina_inicio_locales: typeof pagina_inicio_locales;
  pagina_inicio_rels: typeof pagina_inicio_rels;
  configuracion_sitio_opening_hours: typeof configuracion_sitio_opening_hours;
  configuracion_sitio_opening_hours_locales: typeof configuracion_sitio_opening_hours_locales;
  configuracion_sitio_footer_logos: typeof configuracion_sitio_footer_logos;
  configuracion_sitio_footer_logos_locales: typeof configuracion_sitio_footer_logos_locales;
  configuracion_sitio: typeof configuracion_sitio;
  configuracion_sitio_locales: typeof configuracion_sitio_locales;
  relations_usuarios_sessions: typeof relations_usuarios_sessions;
  relations_usuarios: typeof relations_usuarios;
  relations_archivos: typeof relations_archivos;
  relations_alergenos_locales: typeof relations_alergenos_locales;
  relations_alergenos: typeof relations_alergenos;
  relations_categorias_locales: typeof relations_categorias_locales;
  relations_categorias: typeof relations_categorias;
  relations_platos_etiquetas_locales: typeof relations_platos_etiquetas_locales;
  relations_platos_etiquetas: typeof relations_platos_etiquetas;
  relations_platos_locales: typeof relations_platos_locales;
  relations_platos_rels: typeof relations_platos_rels;
  relations_platos: typeof relations_platos;
  relations_menus_dias_semana: typeof relations_menus_dias_semana;
  relations_menus_locales: typeof relations_menus_locales;
  relations_menus: typeof relations_menus;
  relations_espacios_galeria: typeof relations_espacios_galeria;
  relations_espacios_caracteristicas_locales: typeof relations_espacios_caracteristicas_locales;
  relations_espacios_caracteristicas: typeof relations_espacios_caracteristicas;
  relations_espacios_locales: typeof relations_espacios_locales;
  relations_espacios: typeof relations_espacios;
  relations_banners_locales: typeof relations_banners_locales;
  relations_banners: typeof relations_banners;
  relations_paginas_locales: typeof relations_paginas_locales;
  relations_paginas: typeof relations_paginas;
  relations_experiencias_incluye_locales: typeof relations_experiencias_incluye_locales;
  relations_experiencias_incluye: typeof relations_experiencias_incluye;
  relations_experiencias_locales: typeof relations_experiencias_locales;
  relations_experiencias: typeof relations_experiencias;
  relations_menus_grupo_locales: typeof relations_menus_grupo_locales;
  relations_menus_grupo_rels: typeof relations_menus_grupo_rels;
  relations_menus_grupo: typeof relations_menus_grupo;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_pagina_inicio_galeria_inicio: typeof relations_pagina_inicio_galeria_inicio;
  relations_pagina_inicio_galeria_regalo: typeof relations_pagina_inicio_galeria_regalo;
  relations_pagina_inicio_locales: typeof relations_pagina_inicio_locales;
  relations_pagina_inicio_rels: typeof relations_pagina_inicio_rels;
  relations_pagina_inicio: typeof relations_pagina_inicio;
  relations_configuracion_sitio_opening_hours_locales: typeof relations_configuracion_sitio_opening_hours_locales;
  relations_configuracion_sitio_opening_hours: typeof relations_configuracion_sitio_opening_hours;
  relations_configuracion_sitio_footer_logos_locales: typeof relations_configuracion_sitio_footer_logos_locales;
  relations_configuracion_sitio_footer_logos: typeof relations_configuracion_sitio_footer_logos;
  relations_configuracion_sitio_locales: typeof relations_configuracion_sitio_locales;
  relations_configuracion_sitio: typeof relations_configuracion_sitio;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
